=== simonbaumeler/xml-projekt-blockwoche/xml-database/database.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="energie-data">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="energyTypes"/>
                <xs:element ref="participants"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="energyTypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="energyType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="energyType">
        <xs:complexType>
            <xs:attribute name="key" type="xs:string" />
            <xs:attribute name="display_value" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="participants">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="participant" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="participant">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="startDatetime" type="xs:string"/>

                <xs:element ref="address"/>
                <xs:element ref="energyTransactions"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="address">
        <xs:complexType>
            <xs:all>
                <xs:element name="firstname" type="xs:string"/>
                <xs:element name="middlename" type="xs:string"/>
                <xs:element name="lastname" type="xs:string"/>
                <xs:element name="street" type="xs:string"/>
                <xs:element name="housenumber" type="xs:string"/>
                <xs:element name="city" type="xs:string"/>
                <xs:element name="state" type="xs:string"/>
                <xs:element name="country" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="energyTransactions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="energyTransaction" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="energyTransaction">
        <xs:complexType>
            <xs:attribute name="energyType" type="xs:string" />
            <xs:attribute name="amount" type="xs:decimal" />
            <xs:attribute name="ratePerUnit" type="rate" />
            <xs:attribute name="timestamp" type="xs:string" />
            <xs:attribute name="priceTotal" type="xs:decimal" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="rate">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== simonbaumeler/xml-projekt-blockwoche/xml-database/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<energie-data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="database.xsd">

    <energyTypes>
        <energyType key="electricity" display_value="ElektrizitÃ¤t" />
        <energyType key="gas" display_value="Gas" />
    </energyTypes>

    <participants>
        <participant>
            <name>HSLU Energy Factory</name>
            <startDatetime>2024-02-07T10:00:00.000</startDatetime>

            <address>
                <firstname>Max</firstname>
                <middlename>Ferdinand</middlename>
                <lastname>Mustermann</lastname>
                <street>Musterstrasse</street>
                <housenumber>1</housenumber>
                <city>Rotkreuz</city>
                <state>Zug</state>
                <country>Switzerland</country>
            </address>

            <energyTransactions>
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="3" ratePerUnit="0.003" timestamp="2024-02-08T14:00:00.000" totalPrice="0.009" />
                <energyTransaction energyType="electricity" amount="-100" ratePerUnit="0.05" timestamp="2024-02-08T19:00:00.000" totalPrice="-5" />
            </energyTransactions>
        </participant>
        <!--<participant>
            <name>FHNW Energy Factory</name>
            <startDatetime>2024-02-07T10:00:00.000</startDatetime>

            <address>
                <firstname>Max</firstname>
                <middlename>Ferdinand</middlename>
                <lastname>Mustermann</lastname>
                <street>Musterstrasse</street>
                <housenumber>1</housenumber>
                <city>Rotkreuz</city>
                <state>Zug</state>
                <country>Switzerland</country>
            </address>

            <energyTransactions>
                <energyTransaction energyType="electricity" amount="-3" ratePerUnit="0.013" timestamp="2024-02-08T14:00:00.000" totalPrice="-0.039" />
                <energyTransaction energyType="electricity" amount="7" ratePerUnit="0.013" timestamp="2024-02-08T14:00:00.000" totalPrice="0.091" />
                <energyTransaction energyType="electricity" amount="-24" ratePerUnit="0.013" timestamp="2024-02-08T14:00:00.000" totalPrice="-0.312" />
            </energyTransactions>
        </participant>-->
    </participants>

</energie-data>
